#pragma once
// IR_ESP8266 — Universal IR Controller web UI
// Kept in a separate .h to avoid Arduino IDE ctags parsing issues on Windows.

static const char HTML_PAGE[] PROGMEM =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>IR Controller</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:'Segoe UI',Tahoma,sans-serif;background:#0d0d1a;color:#e2e8f0;min-height:100vh}"
".hdr{background:linear-gradient(135deg,#1a1a2e,#0f3460);padding:18px 16px 14px;text-align:center;border-bottom:2px solid #3182ce;position:sticky;top:0;z-index:10;box-shadow:0 2px 16px rgba(0,0,0,.6)}"
".hdr h1{font-size:1.35em;color:#63b3ed;letter-spacing:2px;text-transform:uppercase;margin-bottom:4px}"
".online{font-size:.75em;color:#718096;margin-bottom:8px}"
".dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#48bb78;margin-right:5px;animation:pulse 2s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.25}}"
".chips{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}"
".chip{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.1);border-radius:20px;padding:3px 12px;font-size:.76em;color:#a0aec0}"
".chip b{color:#63b3ed}"
".clk{font-size:2.8em;font-weight:700;color:#f6ad55;text-align:center;margin:18px 0 2px;letter-spacing:4px;font-variant-numeric:tabular-nums}"
".dt{text-align:center;color:#718096;font-size:.8em;margin-bottom:2px}"
".wrap{max-width:480px;margin:0 auto;padding:0 12px 40px}"
".card{background:#1a1a2e;border-radius:14px;padding:18px;margin:14px 0;border:1px solid rgba(255,255,255,.07);box-shadow:0 4px 20px rgba(0,0,0,.4)}"
".ct{font-size:.68em;font-weight:700;text-transform:uppercase;letter-spacing:1.8px;color:#718096;margin-bottom:14px}"
/* two-column scheduler grid */
".sg{display:flex;gap:10px;flex-wrap:wrap}"
".sb{flex:1;min-width:130px;background:#0a0a14;border-radius:10px;padding:12px;border:1px solid rgba(255,255,255,.07)}"
".sb-on{border-top:3px solid #3182ce}"
".sb-off{border-top:3px solid #4a5568}"
".sbh{font-size:.8em;font-weight:700;text-align:center;margin-bottom:11px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,.06)}"
".sb-on .sbh{color:#63b3ed}"
".sb-off .sbh{color:#a0aec0}"
".tps{width:100%;display:block;margin:8px 0 10px;background:#0d0d1a;border:1px solid #2d3748;border-radius:8px;padding:8px;color:#e2e8f0;font-size:1em;text-align:center;outline:none;transition:border .2s}"
".tps:focus{border-color:#3182ce}"
".row{display:flex;align-items:center;justify-content:space-between}"
".tl{font-size:.88em;font-weight:500}"
/* Toggle */
".tg{position:relative;display:inline-block;width:46px;height:24px;flex-shrink:0}"
".tg input{opacity:0;width:0;height:0}"
".sl{position:absolute;cursor:pointer;inset:0;background:#2d3748;border-radius:24px;transition:.3s}"
".sl:before{position:absolute;content:'';height:16px;width:16px;left:4px;bottom:4px;background:#fff;border-radius:50%;transition:.3s}"
"input:checked+.sl{background:#3182ce}"
"input:checked+.sl:before{transform:translateX(22px)}"
/* Buttons */
".btn{width:100%;padding:11px;border:none;border-radius:10px;font-size:.9em;font-weight:600;cursor:pointer;transition:all .18s;margin-top:10px;letter-spacing:.3px}"
".bon{background:rgba(49,130,206,.15);color:#63b3ed;border:1px solid rgba(49,130,206,.35);width:100%;padding:9px;border-radius:8px;font-size:.8em;font-weight:600;cursor:pointer;transition:all .18s}"
".bon:hover{background:rgba(49,130,206,.28);color:#90cdf4}"
".boff{background:rgba(74,85,104,.2);color:#a0aec0;border:1px solid rgba(74,85,104,.45);width:100%;padding:9px;border-radius:8px;font-size:.8em;font-weight:600;cursor:pointer;transition:all .18s}"
".boff:hover{background:rgba(74,85,104,.35);color:#cbd5e0}"
".bprimary{background:linear-gradient(135deg,#2b6cb0,#1a365d);color:#fff;box-shadow:0 3px 10px rgba(43,108,176,.4)}"
".bprimary:hover{opacity:.87;transform:translateY(-1px)}"
".bsec{background:rgba(255,255,255,.08);color:#a0aec0;border:1px solid rgba(255,255,255,.1)}"
".bsec:hover{background:rgba(255,255,255,.14);color:#e2e8f0}"
".bdanger{background:rgba(233,69,96,.1);color:#e94560;border:1px solid rgba(233,69,96,.28)}"
".bdanger:hover{background:rgba(233,69,96,.2)}"
/* Inputs */
".ig{margin-top:12px}"
".ig label{font-size:.7em;color:#718096;display:block;margin-bottom:5px;font-weight:700;text-transform:uppercase;letter-spacing:1.1px}"
".ig input,.ig select{width:100%;background:#0a0a14;border:1px solid #2d3748;border-radius:9px;padding:10px 12px;color:#e2e8f0;font-size:.9em;outline:none;transition:border .2s}"
".ig input:focus,.ig select:focus{border-color:#3182ce;box-shadow:0 0 0 2px rgba(49,130,206,.15)}"
".ig select option{background:#1a1a2e}"
".mono{font-family:monospace;letter-spacing:.5px}"
".div{height:1px;background:rgba(255,255,255,.07);margin:14px 0}"
/* Protocol info badge */
".pbadge{display:inline-block;font-size:.68em;color:#718096;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:8px;padding:2px 8px;margin-left:6px;vertical-align:middle}"
/* Presets */
".preset-wrap{margin-top:12px}"
".preset-wrap p{font-size:.7em;color:#718096;font-weight:700;text-transform:uppercase;letter-spacing:1.1px;margin-bottom:7px}"
".preset{display:inline-block;background:rgba(49,130,206,.1);border:1px solid rgba(49,130,206,.25);border-radius:14px;padding:4px 11px;font-size:.75em;color:#63b3ed;cursor:pointer;margin:3px 3px 0 0;transition:all .18s}"
".preset:hover{background:rgba(49,130,206,.22)}"
/* IR section headers */
".isec-hdr{font-size:.72em;font-weight:700;padding-bottom:8px;margin-bottom:8px;border-bottom:1px solid rgba(255,255,255,.07)}"
".isec-on{color:#63b3ed}"
".isec-off{color:#a0aec0}"
/* Toast */
".toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#2d3748;color:#e2e8f0;padding:10px 20px;border-radius:22px;font-size:.85em;box-shadow:0 4px 24px rgba(0,0,0,.6);display:none;z-index:999;border-left:4px solid #3182ce;white-space:nowrap;max-width:92vw;overflow:hidden;text-overflow:ellipsis}"
"</style></head><body>"

/* ── Header ── */
"<div class=\"hdr\">"
"<h1>&#128268; IR Controller</h1>"
"<div class=\"online\"><span class=\"dot\"></span>Online</div>"
"<div class=\"chips\">"
"<div class=\"chip\">IP <b id=\"ip\">&mdash;</b></div>"
"<div class=\"chip\">&#127968; <b id=\"host\">&mdash;</b>.local</div>"
"<div class=\"chip\">&#128268; <b id=\"devName\">&mdash;</b></div>"
"</div></div>"

/* ── Clock ── */
"<div class=\"wrap\">"
"<div class=\"clk\" id=\"clk\">--:--:--</div>"
"<div class=\"dt\" id=\"dt\">Syncing&hellip;</div>"

/* ── Scheduler ── */
"<div class=\"card\">"
"<div class=\"ct\">&#9201; Scheduler</div>"
"<div class=\"sg\">"
  "<div class=\"sb sb-on\">"
  "<div class=\"sbh\">&#9889; Power ON</div>"
  "<div class=\"row\"><span class=\"tl\">Enable</span>"
  "<label class=\"tg\"><input type=\"checkbox\" id=\"onEnabled\" onchange=\"toggleOn()\"><span class=\"sl\"></span></label></div>"
  "<input type=\"time\" class=\"tps\" id=\"onTime\">"
  "<button class=\"bon\" onclick=\"saveOn()\">&#128190; Save</button>"
  "</div>"
  "<div class=\"sb sb-off\">"
  "<div class=\"sbh\">&#127769; Power OFF</div>"
  "<div class=\"row\"><span class=\"tl\">Enable</span>"
  "<label class=\"tg\"><input type=\"checkbox\" id=\"offEnabled\" onchange=\"toggleOff()\"><span class=\"sl\"></span></label></div>"
  "<input type=\"time\" class=\"tps\" id=\"offTime\">"
  "<button class=\"boff\" onclick=\"saveOff()\">&#128190; Save</button>"
  "</div>"
"</div></div>"

/* ── Manual ── */
"<div class=\"card\">"
"<div class=\"ct\">&#128171; Manual Control</div>"
"<div style=\"display:flex;gap:10px\">"
"<button class=\"btn bon\" style=\"margin-top:0;padding:13px\" onclick=\"sendOn()\">&#9889; Send ON</button>"
"<button class=\"btn boff\" style=\"margin-top:0;padding:13px\" onclick=\"sendOff()\">&#127769; Send OFF</button>"
"</div></div>"

/* ── IR Device ── */
"<div class=\"card\">"
"<div class=\"ct\">&#128268; IR Device</div>"

/* Presets */
"<div class=\"preset-wrap\">"
"<p>Quick Presets</p>"
"<span class=\"preset\" onclick=\"loadP(0)\">LG AC</span>"
"<span class=\"preset\" onclick=\"loadP(1)\">LG TV</span>"
"<span class=\"preset\" onclick=\"loadP(2)\">Samsung TV</span>"
"<span class=\"preset\" onclick=\"loadP(3)\">Sony TV</span>"
"<span class=\"preset\" onclick=\"loadP(4)\">Panasonic TV</span>"
"<span class=\"preset\" onclick=\"loadP(5)\">Custom&hellip;</span>"
"</div>"
"<div style=\"margin-top:9px;font-size:.72em;line-height:1.55;color:#718096;background:rgba(255,255,255,.04);border-radius:8px;padding:8px 10px;border-left:3px solid #3182ce\">"
"<b style=\"color:#63b3ed\">TV remotes</b> use a single <b>power toggle</b> code &mdash; the same hex value turns the device ON and OFF. "
"Both fields are filled identically for TV presets.<br>"
"<b style=\"color:#a0aec0\">AC remotes</b> often send separate ON and OFF codes. "
"Verify with your remote using an IR receiver if the preset does not work."
"</div>"
"<div class=\"div\"></div>"

/* Device name + protocol */
"<div class=\"ig\"><label>Device Name</label>"
"<input type=\"text\" id=\"devName_inp\" maxlength=\"31\" placeholder=\"e.g. Living Room AC\"></div>"
"<div class=\"ig\"><label>Protocol <span class=\"pbadge\" id=\"protoInfo\"></span></label>"
"<select id=\"proto\" onchange=\"onProtoChange()\">"
"<option value=\"NEC\">NEC &mdash; 32-bit (LG TV, many brands)</option>"
"<option value=\"LG\">LG &mdash; 28-bit (LG AC)</option>"
"<option value=\"LG2\">LG2 &mdash; 28-bit (LG AC newer)</option>"
"<option value=\"SAMSUNG\">Samsung &mdash; 32-bit (Samsung TV / AC)</option>"
"<option value=\"SONY\">Sony &mdash; 12/15/20-bit (Sony devices)</option>"
"<option value=\"RC5\">RC5 &mdash; 13-bit (Philips)</option>"
"<option value=\"RC6\">RC6 &mdash; 20-bit (Philips newer)</option>"
"<option value=\"PANASONIC\">Panasonic &mdash; 48-bit (Panasonic TV)</option>"
"<option value=\"JVC\">JVC &mdash; 16-bit (JVC)</option>"
"<option value=\"SHARP\">Sharp &mdash; 15-bit (Sharp TV)</option>"
"<option value=\"DENON\">Denon &mdash; 14-bit (Denon AV)</option>"
"<option value=\"COOLIX\">Coolix &mdash; 24-bit (Coolix / Midea AC)</option>"
"<option value=\"MITSUBISHI\">Mitsubishi &mdash; 16-bit (Mitsubishi TV)</option>"
"<option value=\"WHYNTER\">Whynter &mdash; 32-bit (Whynter AC)</option>"
"<option value=\"DAIKIN\">Daikin &mdash; 35-byte state (Daikin split AC)</option>"
"</select></div>"

"<div id=\"daikinNote\" style=\"display:none;margin-top:10px;font-size:.72em;line-height:1.55;color:#718096;background:rgba(246,173,85,.06);border-radius:8px;padding:9px 11px;border-left:3px solid #f6ad55\">"
"<b style=\"color:#f6ad55\">Daikin uses a 35-byte full-state packet (70 hex chars) &mdash; not a simple code.</b><br>"
"The preset provides a typical default (Auto 25&deg;C, fan auto). For exact codes, capture with a TSOP1838 receiver and IRrecvDumpV2 example."
"</div>"
"<div class=\"div\"></div>"

/* ON code */
"<div style=\"margin-bottom:4px\" class=\"isec-hdr isec-on\">&#9889; ON Command</div>"
"<div style=\"display:flex;gap:8px\">"
"<div class=\"ig\" style=\"flex:1;margin-top:0\"><label>Hex Code</label>"
"<input type=\"text\" id=\"onCode\" class=\"mono\" maxlength=\"70\" placeholder=\"e.g. 88C0051 (or 70-char Daikin state)\" autocapitalize=\"none\" spellcheck=\"false\"></div>"
"<div class=\"ig\" style=\"width:72px;margin-top:0\"><label>Bits</label>"
"<input type=\"number\" id=\"onBits\" min=\"8\" max=\"64\" placeholder=\"28\"></div>"
"</div>"
"<button class=\"btn bon\" style=\"margin-top:6px\" onclick=\"testCode('on')\">&#9654; Test ON Now</button>"

"<div class=\"div\"></div>"

/* OFF code */
"<div style=\"margin-bottom:4px\" class=\"isec-hdr isec-off\">&#127769; OFF Command</div>"
"<div style=\"display:flex;gap:8px\">"
"<div class=\"ig\" style=\"flex:1;margin-top:0\"><label>Hex Code</label>"
"<input type=\"text\" id=\"offCode\" class=\"mono\" maxlength=\"70\" placeholder=\"e.g. 88C0051 (or 70-char Daikin state)\" autocapitalize=\"none\" spellcheck=\"false\"></div>"
"<div class=\"ig\" style=\"width:72px;margin-top:0\"><label>Bits</label>"
"<input type=\"number\" id=\"offBits\" min=\"8\" max=\"64\" placeholder=\"28\"></div>"
"</div>"
"<button class=\"btn boff\" style=\"margin-top:6px\" onclick=\"testCode('off')\">&#9654; Test OFF Now</button>"

"<div class=\"div\"></div>"
"<button class=\"btn bprimary\" onclick=\"saveDevice()\">&#128190;&nbsp; Save Device Config</button>"
"</div>"

/* ── Settings ── */
"<div class=\"card\">"
"<div class=\"ct\">&#9881; Settings</div>"
"<div class=\"ig\"><label>Device Hostname (mDNS)</label>"
"<input type=\"text\" id=\"mdns\" maxlength=\"31\" placeholder=\"ir-remote\" autocapitalize=\"none\" autocomplete=\"off\" spellcheck=\"false\"></div>"
"<div class=\"ig\"><label>UTC Offset in minutes &mdash; 330=IST | 0=UTC | -300=EST</label>"
"<input type=\"number\" id=\"utc\" min=\"-720\" max=\"840\" placeholder=\"330\"></div>"
"<button class=\"btn bsec\" style=\"margin-top:14px\" onclick=\"saveSettings()\">&#10003;&nbsp; Save Settings</button>"
"<div class=\"div\"></div>"
"<button class=\"btn bdanger\" onclick=\"confirmReset()\">&#9888;&nbsp; Reset WiFi &amp; Restart</button>"
"</div>"

"<div style=\"text-align:center;padding:20px 0 8px;font-size:.7em;color:#4a5568;border-top:1px solid rgba(255,255,255,.05);margin-top:8px\">"
"Developed by <b style=\"color:#718096\">Naveen Surisetty</b>"
"</div>"

"</div>" /* wrap */
"<div class=\"toast\" id=\"toast\"></div>"

/* ── Script ── */
"<script>"
"'use strict';"
"let ci,base,fetchedAt;"

/* Preset data: [name, protocol, onCode, onBits, offCode, offBits] */
"const PRESETS=["
// AC presets — ON and OFF are different codes
"['LG AC',        'LG',       '88C00B7',     28,'88C0051',      28],"
// TV presets — power is a TOGGLE (same code turns on AND off)
"['LG TV',        'NEC',      '20DF10EF',    32,'20DF10EF',     32],"
"['Samsung TV',   'SAMSUNG',  'E0E040BF',    32,'E0E040BF',     32],"
"['Sony TV',      'SONY',     'A90',         12,'A90',           12],"
"['Panasonic TV', 'PANASONIC','400401100101',48,'400401100101',  48],"
"['Daikin AC',    'DAIKIN',   '11DA27000000301411DA27000000341411DA2700002800003C00A0000000000000000006',35,"
                              "'11DA27000000301411DA27000000341411DA2700002800003C00A0000000000000000006',35],"
"['Custom',       'NEC',      '',            32,'',              32]"
"];"

"const PROTO_BITS={NEC:32,LG:28,LG2:28,SAMSUNG:32,SONY:12,RC5:13,RC6:20,PANASONIC:48,JVC:16,SHARP:15,DENON:14,COOLIX:24,MITSUBISHI:16,WHYNTER:32,DAIKIN:35};"

"async function load(){"
"try{"
"const r=await fetch('/api/status');"
"if(!r.ok)throw new Error(r.status);"
"const d=await r.json();"
"document.getElementById('ip').textContent=d.ip||'?';"
"document.getElementById('host').textContent=d.mdnsName||'?';"
"document.getElementById('devName').textContent=d.devName||'?';"
"document.getElementById('devName_inp').value=d.devName||'';"
"document.getElementById('proto').value=d.protocol||'NEC';"
"updateProtoInfo(d.protocol);"
"document.getElementById('onCode').value=d.onCode||'';"
"document.getElementById('onBits').value=d.onBits||28;"
"document.getElementById('offCode').value=d.offCode||'';"
"document.getElementById('offBits').value=d.offBits||28;"
"document.getElementById('onTime').value=d.onTime||'08:00';"
"document.getElementById('offTime').value=d.offTime||'22:00';"
"document.getElementById('onEnabled').checked=d.onEnabled;"
"document.getElementById('offEnabled').checked=d.offEnabled;"
"document.getElementById('mdns').value=d.mdnsName||'';"
"document.getElementById('utc').value=d.utcOffsetMin||330;"
"base=d.epochTime;fetchedAt=Math.floor(Date.now()/1000);"
"if(ci)clearInterval(ci);ci=setInterval(tick,1000);tick();"
"}catch(e){console.error(e);setTimeout(load,2000);}}"

"function tick(){"
"if(!base)return;"
"const n=base+(Math.floor(Date.now()/1000)-fetchedAt);"
"const d=new Date(n*1000);"
"const p=x=>String(x).padStart(2,'0');"
"document.getElementById('clk').textContent=p(d.getUTCHours())+':'+p(d.getUTCMinutes())+':'+p(d.getUTCSeconds());"
"const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];"
"const mos=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];"
"document.getElementById('dt').textContent=days[d.getUTCDay()]+' '+d.getUTCDate()+' '+mos[d.getUTCMonth()]+' '+d.getUTCFullYear();}"

"function updateProtoInfo(p){"
"const b=PROTO_BITS[p];"
"document.getElementById('protoInfo').textContent=b?(b+'-bit'):'';}"

"function onProtoChange(){"
"const p=document.getElementById('proto').value;"
"updateProtoInfo(p);"
"const b=PROTO_BITS[p];"
"if(b){document.getElementById('onBits').value=b;document.getElementById('offBits').value=b;}"
"const n=document.getElementById('daikinNote');"
"if(n)n.style.display=p==='DAIKIN'?'block':'none';}"

"function loadP(i){"
"const x=PRESETS[i];"
"document.getElementById('devName_inp').value=x[0];"
"document.getElementById('proto').value=x[1];"
"updateProtoInfo(x[1]);"
"document.getElementById('onCode').value=x[2];"
"document.getElementById('onBits').value=x[3];"
"document.getElementById('offCode').value=x[4];"
"document.getElementById('offBits').value=x[5];"
"toast('Preset: '+x[0]+' loaded \u2014 review codes then Save');}"

"async function post(u,d){return fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});}"

"function valHex(h){return h.length>0&&h.length<=70&&/^[0-9a-fA-F]+$/.test(h);}"

"async function saveDevice(){"
"const name=document.getElementById('devName_inp').value.trim();"
"const proto=document.getElementById('proto').value;"
"const oc=document.getElementById('onCode').value.trim().toUpperCase();"
"const ob=parseInt(document.getElementById('onBits').value)||28;"
"const fc=document.getElementById('offCode').value.trim().toUpperCase();"
"const fb=parseInt(document.getElementById('offBits').value)||28;"
"if(!name){toast('Device name required');return;}"
"if(oc&&!valHex(oc)){toast('ON code: hex chars only, max 12');return;}"
"if(fc&&!valHex(fc)){toast('OFF code: hex chars only, max 12');return;}"
"await post('/api/settings',{devName:name,protocol:proto,onCode:oc,onBits:ob,offCode:fc,offBits:fb});"
"document.getElementById('devName').textContent=name;"
"toast('Device saved \u2014 '+name+' ['+proto+']');"
"setTimeout(load,600);}"

"async function testCode(which){"
"const code=document.getElementById(which==='on'?'onCode':'offCode').value.trim().toUpperCase();"
"const bits=parseInt(document.getElementById(which==='on'?'onBits':'offBits').value)||28;"
"const proto=document.getElementById('proto').value;"
"if(!valHex(code)){toast('Enter a valid hex code first');return;}"
"toast('Sending test '+(which==='on'?'ON':'OFF')+'\u2026');"
"const r=await post('/api/send-test',{protocol:proto,code:code,bits:bits});"
"toast(r.ok?'\u2714 Sent \u2014 did the device respond?':'\u26A0 Failed');}"

"async function toggleOn(){"
"await post('/api/settings',{onEnabled:document.getElementById('onEnabled').checked});"
"toast(document.getElementById('onEnabled').checked?'ON scheduler enabled':'ON scheduler off');}"
"async function toggleOff(){"
"await post('/api/settings',{offEnabled:document.getElementById('offEnabled').checked});"
"toast(document.getElementById('offEnabled').checked?'OFF scheduler enabled':'OFF scheduler off');}"
"async function saveOn(){"
"const t=document.getElementById('onTime').value;if(!t){toast('Pick ON time');return;}"
"await post('/api/settings',{onTime:t});toast('ON time saved \u2014 '+t);}"
"async function saveOff(){"
"const t=document.getElementById('offTime').value;if(!t){toast('Pick OFF time');return;}"
"await post('/api/settings',{offTime:t});toast('OFF time saved \u2014 '+t);}"
"async function sendOn(){await post('/api/send-on',{});toast('\u26A1 ON command sent');}"
"async function sendOff(){await post('/api/send-off',{});toast('OFF command sent');}"

"async function saveSettings(){"
"const name=document.getElementById('mdns').value.trim();"
"if(!name){toast('Hostname required');return;}"
"if(!/^[a-zA-Z0-9-]+$/.test(name)){toast('Hostname: letters, numbers, hyphens only');return;}"
"await post('/api/settings',{mdnsName:name,utcOffsetMin:parseInt(document.getElementById('utc').value)||330});"
"toast('Settings saved \u2014 hostname applies after restart');setTimeout(load,600);}"

"async function confirmReset(){"
"if(!confirm('Reset WiFi credentials and restart?'))return;"
"await post('/api/reset-wifi',{});toast('Resetting\u2026');}"

"function toast(msg){"
"const el=document.getElementById('toast');"
"el.innerHTML=msg;el.style.display='block';"
"clearTimeout(el._t);el._t=setTimeout(()=>el.style.display='none',3200);}"

"load();"
"</script></body></html>";
